spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

discovery-server:
  startup:
    require-compose-profile: true
