spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_api
    username: payment_api
    password: payment_api_pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="payment-api" password="${PAYMENT_API_KAFKA_PASSWORD}";'

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVER_PORT:8761}/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5

payment-api:
  schema-registry:
    url: http://localhost:8081
  disputes:
    minio:
      endpoint: http://localhost:${MINIO_API_PORT:9000}
      access-key: ${MINIO_ROOT_USER:minioadmin}
      secret-key: ${MINIO_ROOT_PASSWORD}

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
