spring:
  application:
    name: payment-api

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      retries: 2147483647

      batch-size: 32768

      compression-type: zstd

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

        linger.ms: 10

        spring.json.add.type.headers: false

    consumer:
      auto-offset-reset: latest

server:
  port: 8085

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0

payment-api:
  kafka:
    payment-requested-topic: payments.payment-requested.v1
    merchant-config-changed-topic: merchants.merchant-config-changed.v1
    provider-status-query-topic: psp.provider-status-query.v1
    provider-status-reply-topic: psp.provider-status-reply.v1
    payment-status-changed-topic: payments.payment-status-changed.v1
    payment-status-view-group-id: payment-api.status-view.v1
    merchant-view-group-id: payment-api.merchant-view.v1
    dispute-opened-topic: disputes.dispute-opened.v1
    refund-status-changed-topic: refunds.refund-status-changed.v1
    refund-completed-topic: refunds.refund-completed.v1
    refund-failed-topic: refunds.refund-failed.v1
    funds-reserved-topic: refunds.funds-reserved.v1
    refund-status-view-group-id: payment-api.refund-status-view.v1
    refund-completed-view-group-id: payment-api.refund-completed-view.v1
    refund-failed-view-group-id: payment-api.refund-failed-view.v1
    refund-funds-reserved-view-group-id: payment-api.refund-funds-reserved-view.v1
  expiration:
    sweep-interval: PT5S

  disputes:
    claim-check-threshold-bytes: 524288
    claim-check-enabled: true
    minio:
      bucket: disputes

