spring:
  application:
    name: ledger

  kafka:

    consumer:
      group-id: ledger.v1

      auto-offset-reset: earliest

      properties:
        max.poll.records: 50
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 3000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 2147483647
      batch-size: 32768
      compression-type: zstd
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
        schema.registry.url: ${ledger.schema-registry.url}
        auto.register.schemas: true

server:
  port: 8087

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0

ledger:
  instance-id: 0

  fail-after-produce: false

  kafka:
    payment-status-changed-topic: payments.payment-status-changed.v1
    ledger-entry-recorded-topic: ledger.ledger-entry-recorded.v1

    refund-requested-topic: refunds.refund-requested.v1
    funds-reserved-topic: refunds.funds-reserved.v1
    refund-completed-topic: refunds.refund-completed.v1
    refund-failed-topic: refunds.refund-failed.v1
    reservation-released-topic: refunds.reservation-released.v1

    transactional-id-prefix: ledger-tx-${ledger.instance-id}-

  refund:
    reservation-ttl: PT2M
    sweep-interval: PT10S

  dlq-replay:
    dlq-topic: payments.payment-status-changed.v1.ledger.dlq
    consumer-group: ledger.dlq-replay.v1
    max-batch-size: 50
    poll-timeout-ms: 2000

