spring:
  application:
    name: webhook-notifier

  kafka:

    consumer:
      auto-offset-reset: earliest
      properties:
        max.poll.records: 10
        max.poll.interval.ms: 300000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 3000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      batch-size: 32768
      compression-type: zstd
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
        spring.json.add.type.headers: false

  data:
    mongodb:
      auto-index-creation: false

server:
  port: 8088

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0

webhook-notifier:
  kafka:
    payment-status-changed-topic: payments.payment-status-changed.v1
    refund-completed-topic: refunds.refund-completed.v1
    refund-failed-topic: refunds.refund-failed.v1
    refund-status-changed-topic: refunds.refund-status-changed.v1
    delivery-requested-topic: webhooks.webhook-delivery-requested.v2
    retry-5s-topic: webhooks.webhook-delivery-requested.v2.retry.5s
    retry-1m-topic: webhooks.webhook-delivery-requested.v2.retry.1m
    retry-15m-topic: webhooks.webhook-delivery-requested.v2.retry.15m
    dlq-topic: webhooks.webhook-delivery-requested.v2.dlq
    merchant-config-changed-topic: merchants.merchant-config-changed.v1
    planner-group-id: webhook-notifier.planner.v1
    executor-group-id: webhook-notifier.executor.v1
    merchant-view-group-id: webhook-notifier.merchant-view.v1

    deserialization-error-handling-enabled: true

  retry:
    delay-5s-ms: 5000
    delay-1m-ms: 60000
    delay-15m-ms: 900000

  dlq-replay:
    consumer-group: webhook-notifier.dlq-replay.v1
    max-batch-size: 50
    poll-timeout-ms: 2000

  merchant-client:
    base-url: http://localhost:8088
    webhook-path: /simulated-merchant/webhooks/{merchantId}
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

  mongo:
    attempt-log-ttl-seconds: 2592000

  simulated-merchant:
    forced-outcome: NONE
    server-error-rate: 0.0
    client-error-rate: 0.0
    timeout-rate: 0.0
    latency-ms: 50
    timeout-delay-ms: 6000

