spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="realtime-gateway" password="${REALTIME_GATEWAY_KAFKA_PASSWORD}";'

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVER_PORT:8761}/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5

realtime-gateway:
  schema-registry:
    url: http://localhost:8081

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
