spring:
  application:
    name: realtime-gateway

  kafka:
    consumer:
      auto-offset-reset: latest
      properties:
        max.poll.records: 50
        session.timeout.ms: 45000
        heartbeat.interval.ms: 3000

server:
  port: 8090

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0

realtime-gateway:
  kafka:
    payment-requested-topic: payments.payment-requested.v1
    payment-status-changed-topic: payments.payment-status-changed.v1
    refund-requested-topic: refunds.refund-requested.v1
    funds-reserved-topic: refunds.funds-reserved.v1
    refund-completed-topic: refunds.refund-completed.v1
    refund-failed-topic: refunds.refund-failed.v1
    reservation-released-topic: refunds.reservation-released.v1

  sse:
    timeout-ms: 300000
