eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVER_PORT:8761}/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5

spring:
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-api
              uri: lb://payment-api
              predicates:
                - Path=/api/payments/**,/api/merchants/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: paymentApiCB
                    fallbackUri: forward:/fallback/payment-api
            - id: ledger
              uri: lb://ledger
              predicates:
                - Path=/api/refunds/**
            - id: ledger-dlq
              uri: lb://ledger
              predicates:
                - Path=/api/ledger/**
              filters:
                - StripPrefix=2
            - id: webhook-notifier
              uri: lb://webhook-notifier
              predicates:
                - Path=/api/webhooks/**
            - id: analytics
              uri: lb://analytics
              predicates:
                - Path=/api/analytics/**
            - id: realtime-gateway
              uri: lb://realtime-gateway
              predicates:
                - Path=/api/realtime/**
            - id: psp-connector
              uri: lb://psp-connector
              predicates:
                - Path=/api/psp-connector/**
              filters:
                - StripPrefix=2

management:
  otlp:
    tracing:
      endpoint: http://localhost:${TEMPO_OTLP_HTTP_PORT:4318}/v1/traces
