spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:5173"
                allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
                allowedHeaders: "*"
                allowCredentials: false

server:
  port: 8000

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    instances:
      paymentApiCB:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      paymentApiCB:
        timeout-duration: 4s

api-gateway:
  startup:
    require-known-profile: true
