spring:
  data:
    redis:
      host: redis.kafka.svc.cluster.local
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-api
              uri: http://payment-api.kafka.svc.cluster.local:8085
              predicates:
                - Path=/api/payments/**,/api/merchants/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: paymentApiCB
                    fallbackUri: forward:/fallback/payment-api
            - id: ledger
              uri: http://ledger.kafka.svc.cluster.local:8087
              predicates:
                - Path=/api/refunds/**
            - id: ledger-dlq
              uri: http://ledger.kafka.svc.cluster.local:8087
              predicates:
                - Path=/api/ledger/**
              filters:
                - StripPrefix=2
            - id: webhook-notifier
              uri: http://webhook-notifier.kafka.svc.cluster.local:8088
              predicates:
                - Path=/api/webhooks/**
            - id: analytics
              uri: http://analytics.kafka.svc.cluster.local:8089
              predicates:
                - Path=/api/analytics/**
            - id: realtime-gateway
              uri: http://realtime-gateway.kafka.svc.cluster.local:8090
              predicates:
                - Path=/api/realtime/**
            - id: psp-connector
              uri: http://psp-connector.kafka.svc.cluster.local:8086
              predicates:
                - Path=/api/psp-connector/**
              filters:
                - StripPrefix=2

management:
  otlp:
    tracing:
      endpoint: http://tempo.observability.svc.cluster.local:4318/v1/traces
